{"name": "Проверка ошибки при неверном логине или пароле.Ожидаемый результат: 404", "status": "passed", "parameters": [{"name": "field", "value": "'password'"}, {"name": "invalid_value", "value": "'aunjxqobmb'"}], "start": 1743608242496, "stop": 1743608242669, "uuid": "3221a213-ded7-4f59-a8b9-66d9c7cf22b8", "historyId": "277cf97a75a68f9673aa18ef8bb57c16", "testCaseId": "ea9a450ccbd1454b021935fd27407c1e", "fullName": "tests.test_courier_auth.TestCourierAuth#test_authorization_invalid_login_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_auth"}, {"name": "subSuite", "value": "TestCourierAuth"}, {"name": "host", "value": "DESKTOP-O2PS26S"}, {"name": "thread", "value": "28228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_auth"}]}